Seminar6 필수과제 완료
GO-SOPT-ANDROID/somin_lee pull request #4
Opened 2023-06-02 18:33 UTC by s6m1n

- [x] reqres API 뷰 - 뷰모델 분리하기
- [x] sign up 뷰 - 뷰모델 분리하기
- [x] login 뷰 - 뷰모델 분리하기
- [x] ID/비밀번호 생성 조건 변경
- [x] ID나 비밀번호 생성조건에 맞지 않을 시 회원가입 버튼은 비활성화
- [x] 비밀번호 란에 입력된 값이 조건과 맞지 않는 경우 입력창 하단에 경고문구 및 경고 띄우기

MVVM 어렵네요.. 혼자서 처음 하려니까 머리가 돌아버려..

2023-06-04 14:54 UTC, KwakEuiJin requested changes
급하게 12시 이전까지만 보는거여서 내일 다시 코멘트 남겨놓도록 하겠습니다.

2023-06-04 14:54 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/presentation/fragment/BaseFragment.kt
> +/**BaseFragment 클래스의 생성자에 inflate 매개변수가 추가되었습니다. 이 매개변수는 Inflate<VB> 타입으로 받고, 프래그먼트의 뷰를 인플레이션하는 데 사용됩니다. 이를 통해 BaseFragment 클래스를 상속받을 때 inflate 함수를 직접 지정할 수 있습니다. 또 주어진 코드에서는 VB라는 타입 매개변수를 도입하였습니다. 이
워후 이 엄청나고 새로운 아이는 무엇인가요?!

2023-06-04 14:54 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/presentation/fragment/SearchFragment.kt
> +                        viewModel.setRequestBody(ContentUriRequestBody(requireContext(),imageUriList[2]))
요기 반복되는 로직이 꽤 있는데요, 전체적으로 함축시킬 수 있지 않을까 싶습니다

2023-06-04 14:54 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +        )
startActivity 이후에 finish를 호출해주는 것이 혹시 모를 예외 상황을 막을 수 있을 것 같습니다.

2023-06-05 04:27 UTC, KwakEuiJin requested changes
매주 소민님의 코드를 보면서 느끼는건데요, 정말 엄청나게 항상 성장하시는 것 같아 너무너무 대단합니다. 특히 ViewModel과 View의 연결된 코드를 보면서 어색한 방법이었을텐데 너무 자연스럽게 사용하시는 부분과 세심한 예외처리들이 너무 인상깊었습니다. 총 5번 쏘고 가겠습니다. 🔫 🔫 🔫 🔫 🔫

++ 다음주는 코루틴의 사용과 중복되는 로직의 함수화된 코드를 기대하겠습니다 >< 수고하셨어요~!!

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/interceptor/SoptInterceptor.kt
> +//}
코드 주석은 한줄 당 1000원씩 빠져나간다고 생각하면 지우고싶으실거에요 하핳

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/model/SearchViewModel.kt
> +}
요 함수를 하나로 합칠 수 있는 방법이 있지 않을까요?!? 
Hint : uploadImage의 파라메터에 무언가를 넣어보세요 ^&^

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/model/signup/LoginViewModel.kt
> +            }
어떻게 서버오류라고 단정하시죠?! 하핳 클라의 잘못일수도?!?

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/model/signup/SignUpViewModel.kt
> +
init 블럭을 쓰는 대신에 
```
private val _isButtonEnabled = MutableLiveData<Boolean>(false)
    val isButtonEnabled: LiveData<Boolean> = _isButtonEnabled
```

이렇게 구현할 수 있습니다

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/model/signup/SignUpViewModel.kt
> +    }
성공했을 때 Log만 찍고있습니다! 어떠한 동작이 필요해보여요

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/presentation/fragment/UserFragment.kt
> +        }
여기는 각 기능별로 함수를 좀 더 세분화 시키면 코드가 가독성이 좋아질 것 같습니다

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
>      }
요기는 scope 함수를 이용하면 좋을 것 같아욥~!!

2023-06-05 04:27 UTC, KwakEuiJin commented on app/src/main/res/layout/activity_sign_up.xml
> +    </com.google.android.material.textfield.TextInputLayout>
TextInputLayout까지 와우 진짜 코드 너무 고수의 향기가 납니다

2023-06-07 10:31 UTC, s6m1n commented on app/src/main/java/org/android/go/sopt/presentation/fragment/BaseFragment.kt
> +/**BaseFragment 클래스의 생성자에 inflate 매개변수가 추가되었습니다. 이 매개변수는 Inflate<VB> 타입으로 받고, 프래그먼트의 뷰를 인플레이션하는 데 사용됩니다. 이를 통해 BaseFragment 클래스를 상속받을 때 inflate 함수를 직접 지정할 수 있습니다. 또 주어진 코드에서는 VB라는 타입 매개변수를 도입하였습니다. 이
ㅋㅋㅋㅋㅋ아 ?! 헷갈리지 않으려고 설명을 적어놓았는데 올라와버렸네요,, 지우도록 하겠습니다!

2023-06-07 10:32 UTC, s6m1n commented on app/src/main/java/org/android/go/sopt/presentation/login/LoginActivity.kt
> +        )
그러네요! 이 부분은 수정하도록 하겠습니다👍

2023-06-07 10:33 UTC, s6m1n commented on app/src/main/java/org/android/go/sopt/presentation/fragment/SearchFragment.kt
> +                        viewModel.setRequestBody(ContentUriRequestBody(requireContext(),imageUriList[2]))
세미나 내용을 급하게 따라적느라 이 부분 코드가 굉장히 별로네요.. 이번주차 과제에서 깔끔하게 줄일 수 있도록 고민해보겠습니다!!

2023-06-07 10:34 UTC, s6m1n commented on app/src/main/java/org/android/go/sopt/model/signup/SignUpViewModel.kt
> +
아이쿠 이 간단한 걸 세줄이나 늘려버렸네요! 머쓱,,

2023-06-07 10:38 UTC, s6m1n commented on app/src/main/java/org/android/go/sopt/model/signup/SignUpViewModel.kt
> +    }
제가 아직 뷰모델에 대한 이해가 부족했던 것 같은데, 올바른 MVVM 패턴이라면 해당 부분이 성공 메시지 출력과 LoginActivity로의 이동 등 회원가입 성공시의 로직들을 포함하고 있어야 하는 걸까요?? 저는 이 부분을 액티비티에서 처리해줬거든요..!

2023-06-07 10:40 UTC, s6m1n commented on app/src/main/java/org/android/go/sopt/interceptor/SoptInterceptor.kt
> +//}
세상에 그런 끔찍한...!!! 당장 지워버려야겠어요..

2023-06-07 16:03 UTC, KwakEuiJin commented on app/src/main/java/org/android/go/sopt/model/signup/SignUpViewModel.kt
> +    }
넵넵! 현재는 Activity에서 moveToLogin이라는 함수로 성공/실패에 따른 분기처리 없이 무조건 LoginActivity로 이동하도록 되어있는데요! 만약에 회원가입이 실패했을 때에는 실패 SnackBar를 통해 사용자에게 알려주거나 성공시에만 이동하도록 처리하는 것이 알맞은 방법일 것 같습니다. 

올바른 MVVM 패턴? 이라고 하는게 맞는지는 잘 모르겠지만 성공시 LiveData에 성공여부를 판단할 수 있는 값을 방출해주고 Activity 단에서 LiveData를 구독함으로써 로직을 처리하는 것이 좀 더 올바른 사용방법일 것 같습니다.

2023-06-16 09:00 UTC, merged